//! `cargo xtask rules-doc`: `docs/rules.md`, the rule catalog a reader
//! browses before installing.
//!
//! Rendered from `sightline explain --json` on the release binary, so the
//! catalog is the registry and the measured rows the binary embeds, never a
//! second list. `--check` renders and compares, so the committed file cannot
//! drift from the binary without the `check` stage failing.

use std::collections::BTreeMap;

use anyhow::{Context, Result, bail};
use serde_json::Value;

use crate::corpus::binary;
use crate::paths::workspace_root;

const DOC: &str = "docs/rules.md";

fn field<'a>(v: &'a Value, key: &str) -> &'a str {
    v[key].as_str().unwrap_or_default()
}

/// `tp/n` and its interval for the whole rule where a round judged it, else
/// the first judged arm named, else `unmeasured`.
fn precision_cell(record: &Value) -> String {
    let rows = record["precision"]
        .as_array()
        .map_or(&[][..], Vec::as_slice);
    match rows.first() {
        None => "unmeasured".to_string(),
        Some(s) if field(s, "arm").is_empty() => {
            format!("{}/{} ({})", s["tp"], s["n"], field(s, "interval"))
        }
        Some(s) => format!(
            "{}/{} ({}, `{}` findings)",
            s["tp"],
            s["n"],
            field(s, "interval"),
            field(s, "arm")
        ),
    }
}

fn render(records: &[Value]) -> String {
    let mut out = String::from(
        "# Rules\n\n\
         Every rule the binary runs, with what it checks, the goal it approximates\n\
         and the precision a judged round measured. Generated by `cargo xtask\n\
         rules-doc` from `sightline explain --json`; `sightline explain <id>` prints\n\
         one rule's record at the terminal. Never edit this file by hand.\n\n\
         A rule's **family** names what it prices: trust (declared contracts against\n\
         what callers prove), surface (repeats, clumps and complexity), context (what\n\
         a reader must ingest), perf, tests, and checker (the type checker's own\n\
         verdicts). Its **tier** is how its findings are proved (proved, indexed or\n\
         heuristic). Its **posture** is what `gate` does with them: ratchet blocks\n\
         what a change adds over the committed baseline, report never blocks. Its\n\
         **scope** says which gate runs it: a file rule reads one file and runs in\n\
         the fast gate on every edit; a repo rule reads the whole tree and runs only\n\
         under `audit` and `gate --full`, so a fast gate cannot see what a repo rule\n\
         would block on.\n\n\
         **Precision** is the judged sample, real findings over findings read, with\n\
         the 95% interval that sample supports; the report ranks on a lower bound of\n\
         it, so a rule judged on five sites sits below one judged on two hundred at\n\
         the same fraction. `architecture.md` explains the rounds. Ids are permanent;\n\
         a Rust reading shares its Python sibling's id and slug.\n\n\
         ## Roster\n\n\
         | Id | Slug | Lang | Family | Posture | Tier | Scope | Precision |\n\
         | --- | --- | --- | --- | --- | --- | --- | --- |\n",
    );
    for r in records {
        out.push_str(&format!(
            "| [#{id}](#{id}-{slug}) | `{slug}` | {} | {} | {} | {} | {} | {} |\n",
            field(r, "lang"),
            field(r, "family"),
            field(r, "posture"),
            field(r, "tier"),
            field(r, "scope"),
            precision_cell(r),
            id = field(r, "id"),
            slug = field(r, "slug"),
        ));
    }

    // one section per id, its readings in registry order (py before rs)
    let mut by_id: BTreeMap<u32, Vec<&Value>> = BTreeMap::new();
    for r in records {
        let id: u32 = field(r, "id").parse().unwrap_or(u32::MAX);
        by_id.entry(id).or_default().push(r);
    }
    for readings in by_id.values() {
        let first = readings[0];
        out.push_str(&format!(
            "\n## #{} {}\n\n",
            field(first, "id"),
            field(first, "slug")
        ));
        for r in readings {
            if readings.len() > 1 {
                out.push_str(&format!("### {}\n\n", field(r, "lang")));
            }
            out.push_str(&format!(
                "**Checks:** {}\n\n**Goal:** {}\n\n",
                field(r, "meaning"),
                field(r, "goal")
            ));
            if !field(r, "complement").is_empty() {
                out.push_str(&format!(
                    "**Covered elsewhere:** {}\n\n",
                    field(r, "complement")
                ));
            }
            out.push_str(&format!(
                "Family {}, engine {}, {} tier, posture {}, {} scope.\n\n",
                field(r, "family"),
                field(r, "engine"),
                field(r, "tier"),
                field(r, "posture"),
                field(r, "scope")
            ));
            let rows = r["precision"].as_array().map_or(&[][..], Vec::as_slice);
            if rows.is_empty() {
                out.push_str("Precision: unmeasured.\n\n");
            }
            for s in rows {
                let arm = field(s, "arm");
                let label = if arm.is_empty() {
                    String::new()
                } else {
                    format!("`{arm}` findings ")
                };
                out.push_str(&format!(
                    "Precision: {label}{}/{}, 95% interval {}, seed {}, {}.\n\n",
                    s["tp"],
                    s["n"],
                    field(s, "interval"),
                    s["seed"],
                    field(s, "of")
                ));
            }
            if let Some(c) = r.get("recall").filter(|c| !c.is_null()) {
                out.push_str(&format!(
                    "Recall: {}/{}, {}.\n\n",
                    c["covered"],
                    c["sites"],
                    field(c, "of")
                ));
            }
        }
    }
    out
}

fn records() -> Result<Vec<Value>> {
    let out = std::process::Command::new(binary()?)
        .args(["explain", "--json"])
        .output()
        .context("sightline explain --json")?;
    if !out.status.success() {
        bail!(
            "sightline explain --json failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    Ok(serde_json::from_slice(&out.stdout)?)
}

pub fn main(args: &[&str]) -> Result<u8> {
    let path = workspace_root().join(DOC);
    let text = render(&records()?);
    if args == ["--check"] {
        let have = std::fs::read_to_string(&path).unwrap_or_default();
        if have.replace("\r\n", "\n") == text {
            println!("rules-doc: {DOC} is current");
            return Ok(0);
        }
        println!("rules-doc: {DOC} is stale; run `cargo xtask rules-doc`");
        return Ok(1);
    }
    std::fs::write(&path, text)?;
    println!("rules-doc: wrote {DOC}");
    Ok(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_shared_id_renders_one_section_with_a_heading_per_language() {
        let records = vec![
            serde_json::json!({"id": "11", "slug": "clones", "lang": "py", "family": "surface",
                "engine": "IDX", "tier": "indexed", "posture": "ratchet", "scope": "repo",
                "meaning": "m", "goal": "g", "complement": "",
                "precision": [{"arm": "", "tp": 9, "n": 10, "seed": 1, "of": "round 1",
                    "interval": "0.66-0.99"}],
                "recall": {"covered": 1, "sites": 2, "of": "lists"}}),
            serde_json::json!({"id": "11", "slug": "clones", "lang": "rs", "family": "surface",
                "engine": "IDX", "tier": "indexed", "posture": "report", "scope": "file",
                "meaning": "m", "goal": "g", "complement": "clippy", "precision": [],
                "recall": null}),
        ];
        let doc = render(&records);
        assert!(doc.contains(
            "| [#11](#11-clones) | `clones` | py | surface | ratchet | indexed | repo | 9/10 (0.66-0.99) |"
        ));
        assert!(doc.contains(
            "| [#11](#11-clones) | `clones` | rs | surface | report | indexed | file | unmeasured |"
        ));
        assert_eq!(doc.matches("\n## #11 clones\n").count(), 1);
        assert!(doc.contains("### py\n"));
        assert!(doc.contains("### rs\n"));
        assert!(
            doc.contains(
                "Family surface, engine IDX, indexed tier, posture ratchet, repo scope.\n"
            )
        );
        assert!(doc.contains("Precision: 9/10, 95% interval 0.66-0.99, seed 1, round 1.\n"));
        assert!(doc.contains("Recall: 1/2, lists.\n"));
        assert!(doc.contains("**Covered elsewhere:** clippy\n"));
        assert!(doc.contains("Precision: unmeasured.\n"));
    }
}
